### ISSUE TITLE
Factory reset ReSpeaker without WiFi

### ISSUE THREAD

**Issue by hipitihop** [respeaker/docs#2]
I setup ReSpeaker and connected browser to 192.168.100.1 using Chrome on my Samsung S2 tablet. Unlike the instructions suggested I needed to first set root password, instead it just logged in and went to dashboard. I could not find way to get it into station mode or connect to my WiFi. After playing around and disabling DHCP and also giving it an IP on same subnet as my home LAN i.e 192.168.0.60 I now fail to connect to it at all, but can see SSID on WiFi scan. 

How can I factory reset it without WiFi? Is there a hardware reset switch or do I need usb or serial console. Please give detailed instructions

**Comment by xiongyihui** [comment]
The on-board microcontroller ATmega32u4 can be used as a usb serial console. Just use serial terminal tool like putty to access it (on Windows 10, Linux or Mac, no driver is required.)

**Comment by hipitihop** [comment]
@xiongyihui Thanks,  I have managed to connect the usb serial console from my Linux machine. Is there a command to factory reset the setup ? I'm trying to follow these getting started instructions https://github.com/respeaker/get_started_with_respeaker/wiki and as mentioned at the start of this issue, I never did get prompted for setting the password, and the browser UI looks different and can't find where to set "station mode"

**Comment by hipitihop** [comment]
I have now managed to reset via the serial console by running command `firstboot` So I can access ReSpeaker on default 192.168.100.1 again, but I'm still not getting prompted for setting the password and the browser UI is different to getting started instruction on WiKi, no WAN etc. I'll report if I can manage to get it into "station mode"

**Comment by hipitihop** [comment]
Update: I found https://github.com/respeaker/get_started_with_respeaker/wiki/WiFi I have managed to connect to my home wifi and ReSpeaker now also has internet
